#ifndef CORNERGAME_ENUMS_H
#define CORNERGAME_ENUMS_H

enum StateEnum { STATE_NONE = 0, STATE_QUIT, STATE_START, STATE_PLAY,
                 STATE_MENU, STATE_HIGHSCORE, STATE_RESULTS };

enum SfxEnum { SFX_NONE = 0, SFX_ALERT };

enum MusicEnum { MUSIC_START, MUSIC_MENU, MUSIC_PLAY, MUSIC_HIGHSCORE };

enum ProjEnum { HERO_PROJ, ENEMY_PROJ };

#endif
